Resources:
  LoaderBinanceLambda:
    Properties:
      CodeUri: functions/loader-binance/
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref 'TrdScnTable'
      Handler: loader_binance.lambda_handler
      MemorySize: 128
      Policies:
        - Statement:
            - Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:Query
                - dynamodb:DeleteItem
              Effect: Allow
              Resource:
                - !GetAtt 'TrdScnTable.Arn'
          Version: '2012-10-17'
      ReservedConcurrentExecutions: 1
      Runtime: python3.11
      Timeout: 900
    Type: AWS::Serverless::Function
  LoaderBinanceLambdaInvokePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref 'LoaderBinanceLambda'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'LoaderBinanceLambdaScheduleRule.Arn'
    Type: AWS::Lambda::Permission
  LoaderBinanceLambdaScheduleRule:
    Properties:
      Description: Invoke Binance loader lambda daily
      ScheduleExpression: cron(0 1 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt 'LoaderBinanceLambda.Arn'
          Id: TargetRuleScheduleLambda
          RetryPolicy:
            MaximumRetryAttempts: 2
    Type: AWS::Events::Rule
  LoaderFmpLambda:
    Properties:
      CodeUri: functions/loader-fmp/
      Environment:
        Variables:
          CHART_LOAD_LIMIT: 50
          DDB_TABLE_NAME: !Ref 'TrdScnTable'
          FMP_API_KEY: 7QKqNgh9o8Uc7vM1NTOXEWrb7n2cUMWR
      Handler: loader_fmp.lambda_handler
      MemorySize: 128
      Policies:
        - Statement:
            - Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:Query
                - dynamodb:DeleteItem
              Effect: Allow
              Resource:
                - !GetAtt 'TrdScnTable.Arn'
          Version: '2012-10-17'
      ReservedConcurrentExecutions: 1
      Runtime: python3.11
      Timeout: 900
    Type: AWS::Serverless::Function
  LoaderFmpLambdaInvokePermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref 'LoaderFmpLambda'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'LoaderFmpLambdaScheduleRule.Arn'
    Type: AWS::Lambda::Permission
  LoaderFmpLambdaScheduleRule:
    Properties:
      Description: Invoke FMP loader lambda daily
      ScheduleExpression: cron(0 23 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt 'LoaderFmpLambda.Arn'
          Id: TargetRuleScheduleLambda
          RetryPolicy:
            MaximumRetryAttempts: 2
    Type: AWS::Events::Rule
  TrdScnTable:
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: sort
          KeyType: RANGE
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
Transform: AWS::Serverless-2016-10-31
